<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BangladeshGeoSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $divisions = [
            ['id' => 1, 'name' => 'Dhaka', 'bn_name' => 'ঢাকা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'name' => 'Chattogram', 'bn_name' => 'চট্টগ্রাম', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'name' => 'Rajshahi', 'bn_name' => 'রাজশাহী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'name' => 'Khulna', 'bn_name' => 'খুলনা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'name' => 'Barishal', 'bn_name' => 'বরিশাল', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'name' => 'Sylhet', 'bn_name' => 'সিলেট', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'name' => 'Rangpur', 'bn_name' => 'রংপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'name' => 'Mymensingh', 'bn_name' => 'ময়মনসিংহ', 'created_at' => $now, 'updated_at' => $now],
        ];

        DB::table('divisions')->upsert($divisions, ['id'], ['name', 'bn_name', 'updated_at']);

        $districts = [
            ['id' => 1, 'division_id' => 1, 'name' => 'Dhaka', 'bn_name' => 'ঢাকা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'division_id' => 1, 'name' => 'Gazipur', 'bn_name' => 'গাজীপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'division_id' => 1, 'name' => 'Narayanganj', 'bn_name' => 'নারায়ণগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'division_id' => 1, 'name' => 'Tangail', 'bn_name' => 'টাঙ্গাইল', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'division_id' => 1, 'name' => 'Narsingdi', 'bn_name' => 'নরসিংদী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'division_id' => 1, 'name' => 'Manikganj', 'bn_name' => 'মানিকগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'division_id' => 1, 'name' => 'Munshiganj', 'bn_name' => 'মুন্সীগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'division_id' => 1, 'name' => 'Faridpur', 'bn_name' => 'ফরিদপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'division_id' => 1, 'name' => 'Gopalganj', 'bn_name' => 'গোপালগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'division_id' => 1, 'name' => 'Madaripur', 'bn_name' => 'মাদারীপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'division_id' => 1, 'name' => 'Rajbari', 'bn_name' => 'রাজবাড়ী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'division_id' => 1, 'name' => 'Shariatpur', 'bn_name' => 'শরীয়তপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'division_id' => 1, 'name' => 'Kishoreganj', 'bn_name' => 'কিশোরগঞ্জ', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 14, 'division_id' => 2, 'name' => 'Chattogram', 'bn_name' => 'চট্টগ্রাম', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 15, 'division_id' => 2, 'name' => 'Cox\'s Bazar', 'bn_name' => 'কক্সবাজার', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'division_id' => 2, 'name' => 'Cumilla', 'bn_name' => 'কুমিল্লা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'division_id' => 2, 'name' => 'Feni', 'bn_name' => 'ফেনী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'division_id' => 2, 'name' => 'Brahmanbaria', 'bn_name' => 'ব্রাহ্মণবাড়িয়া', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'division_id' => 2, 'name' => 'Rangamati', 'bn_name' => 'রাঙ্গামাটি', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'division_id' => 2, 'name' => 'Noakhali', 'bn_name' => 'নোয়াখালী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'division_id' => 2, 'name' => 'Chandpur', 'bn_name' => 'চাঁদপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'division_id' => 2, 'name' => 'Lakshmipur', 'bn_name' => 'লক্ষ্মীপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'division_id' => 2, 'name' => 'Khagrachhari', 'bn_name' => 'খাগড়াছড়ি', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'division_id' => 2, 'name' => 'Bandarban', 'bn_name' => 'বান্দরবান', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 25, 'division_id' => 3, 'name' => 'Rajshahi', 'bn_name' => 'রাজশাহী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'division_id' => 3, 'name' => 'Bogura', 'bn_name' => 'বগুড়া', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'division_id' => 3, 'name' => 'Pabna', 'bn_name' => 'পাবনা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'division_id' => 3, 'name' => 'Sirajganj', 'bn_name' => 'সিরাজগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 29, 'division_id' => 3, 'name' => 'Naogaon', 'bn_name' => 'নওগাঁ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'division_id' => 3, 'name' => 'Natore', 'bn_name' => 'নাটোর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'division_id' => 3, 'name' => 'Chapainawabganj', 'bn_name' => 'চাঁপাইনবাবগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'division_id' => 3, 'name' => 'Joypurhat', 'bn_name' => 'জয়পুরহাট', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 33, 'division_id' => 4, 'name' => 'Khulna', 'bn_name' => 'খুলনা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 34, 'division_id' => 4, 'name' => 'Jashore', 'bn_name' => 'যশোর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 35, 'division_id' => 4, 'name' => 'Satkhira', 'bn_name' => 'সাতক্ষীরা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'division_id' => 4, 'name' => 'Kushtia', 'bn_name' => 'কুষ্টিয়া', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'division_id' => 4, 'name' => 'Jhenaidah', 'bn_name' => 'ঝিনাইদহ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'division_id' => 4, 'name' => 'Bagerhat', 'bn_name' => 'বাগেরহাট', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 39, 'division_id' => 4, 'name' => 'Chuadanga', 'bn_name' => 'চুয়াডাঙ্গা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 40, 'division_id' => 4, 'name' => 'Magura', 'bn_name' => 'মাগুরা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 41, 'division_id' => 4, 'name' => 'Meherpur', 'bn_name' => 'মেহেরপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 42, 'division_id' => 4, 'name' => 'Narail', 'bn_name' => 'নড়াইল', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 43, 'division_id' => 5, 'name' => 'Barishal', 'bn_name' => 'বরিশাল', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 44, 'division_id' => 5, 'name' => 'Patuakhali', 'bn_name' => 'পটুয়াখালী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 45, 'division_id' => 5, 'name' => 'Bhola', 'bn_name' => 'ভোলা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 46, 'division_id' => 5, 'name' => 'Pirojpur', 'bn_name' => 'পিরোজপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 47, 'division_id' => 5, 'name' => 'Barguna', 'bn_name' => 'বরগুনা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 48, 'division_id' => 5, 'name' => 'Jhalokati', 'bn_name' => 'ঝালকাঠি', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 49, 'division_id' => 6, 'name' => 'Sylhet', 'bn_name' => 'সিলেট', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 50, 'division_id' => 6, 'name' => 'Moulvibazar', 'bn_name' => 'মৌলভীবাজার', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 51, 'division_id' => 6, 'name' => 'Habiganj', 'bn_name' => 'হবিগঞ্জ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 52, 'division_id' => 6, 'name' => 'Sunamganj', 'bn_name' => 'সুনামগঞ্জ', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 53, 'division_id' => 7, 'name' => 'Rangpur', 'bn_name' => 'রংপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 54, 'division_id' => 7, 'name' => 'Dinajpur', 'bn_name' => 'দিনাজপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 55, 'division_id' => 7, 'name' => 'Gaibandha', 'bn_name' => 'গাইবান্ধা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 56, 'division_id' => 7, 'name' => 'Kurigram', 'bn_name' => 'কুড়িগ্রাম', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 57, 'division_id' => 7, 'name' => 'Lalmonirhat', 'bn_name' => 'লালমনিরহাট', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 58, 'division_id' => 7, 'name' => 'Nilphamari', 'bn_name' => 'নীলফামারী', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 59, 'division_id' => 7, 'name' => 'Panchagarh', 'bn_name' => 'পঞ্চগড়', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 60, 'division_id' => 7, 'name' => 'Thakurgaon', 'bn_name' => 'ঠাকুরগাঁও', 'created_at' => $now, 'updated_at' => $now],

            ['id' => 61, 'division_id' => 8, 'name' => 'Mymensingh', 'bn_name' => 'ময়মনসিংহ', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 62, 'division_id' => 8, 'name' => 'Jamalpur', 'bn_name' => 'জামালপুর', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 63, 'division_id' => 8, 'name' => 'Netrokona', 'bn_name' => 'নেত্রকোণা', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 64, 'division_id' => 8, 'name' => 'Sherpur', 'bn_name' => 'শেরপুর', 'created_at' => $now, 'updated_at' => $now],
        ];

        DB::table('districts')->upsert($districts, ['id'], ['division_id', 'name', 'bn_name', 'updated_at']);

        $upazilas = [
            ['district_id' => 1, 'name' => 'Dhanmondi', 'bn_name' => 'ধানমন্ডি'],
            ['district_id' => 1, 'name' => 'Mirpur', 'bn_name' => 'মিরপুর'],
            ['district_id' => 1, 'name' => 'Gulshan', 'bn_name' => 'গুলশান'],
            ['district_id' => 1, 'name' => 'Banani', 'bn_name' => 'বনানী'],
            ['district_id' => 1, 'name' => 'Uttara', 'bn_name' => 'উত্তরা'],
            ['district_id' => 1, 'name' => 'Mohammadpur', 'bn_name' => 'মোহাম্মদপুর'],
            ['district_id' => 1, 'name' => 'Tejgaon', 'bn_name' => 'তেজগাঁও'],
            ['district_id' => 1, 'name' => 'Motijheel', 'bn_name' => 'মতিঝিল'],
            ['district_id' => 1, 'name' => 'Ramna', 'bn_name' => 'রমনা'],
            ['district_id' => 1, 'name' => 'Shahbagh', 'bn_name' => 'শাহবাগ'],
            ['district_id' => 1, 'name' => 'Badda', 'bn_name' => 'বাড্ডা'],
            ['district_id' => 1, 'name' => 'Khilgaon', 'bn_name' => 'খিলগাঁও'],
            ['district_id' => 1, 'name' => 'Paltan', 'bn_name' => 'পল্টন'],
            ['district_id' => 1, 'name' => 'Lalbagh', 'bn_name' => 'লালবাগ'],
            ['district_id' => 1, 'name' => 'Jatrabari', 'bn_name' => 'যাত্রাবাড়ী'],
            ['district_id' => 1, 'name' => 'Savar', 'bn_name' => 'সাভার'],
            ['district_id' => 1, 'name' => 'Dhamrai', 'bn_name' => 'ধামরাই'],
            ['district_id' => 1, 'name' => 'Keraniganj', 'bn_name' => 'কেরানীগঞ্জ'],
            ['district_id' => 1, 'name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ'],
            ['district_id' => 1, 'name' => 'Dohar', 'bn_name' => 'দোহার'],

            ['district_id' => 2, 'name' => 'Gazipur Sadar', 'bn_name' => 'গাজীপুর সদর'],
            ['district_id' => 2, 'name' => 'Tongi', 'bn_name' => 'টঙ্গী'],
            ['district_id' => 2, 'name' => 'Kaliakair', 'bn_name' => 'কালিয়াকৈর'],
            ['district_id' => 2, 'name' => 'Sreepur', 'bn_name' => 'শ্রীপুর'],
            ['district_id' => 2, 'name' => 'Kapasia', 'bn_name' => 'কাপাসিয়া'],
            ['district_id' => 2, 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],

            ['district_id' => 3, 'name' => 'Narayanganj Sadar', 'bn_name' => 'নারায়ণগঞ্জ সদর'],
            ['district_id' => 3, 'name' => 'Bandar', 'bn_name' => 'বন্দর'],
            ['district_id' => 3, 'name' => 'Rupganj', 'bn_name' => 'রূপগঞ্জ'],
            ['district_id' => 3, 'name' => 'Sonargaon', 'bn_name' => 'সোনারগাঁও'],
            ['district_id' => 3, 'name' => 'Araihazar', 'bn_name' => 'আড়াইহাজার'],

            ['district_id' => 4, 'name' => 'Tangail Sadar', 'bn_name' => 'টাঙ্গাইল সদর'],
            ['district_id' => 4, 'name' => 'Mirzapur', 'bn_name' => 'মির্জাপুর'],
            ['district_id' => 4, 'name' => 'Gopalpur', 'bn_name' => 'গোপালপুর'],
            ['district_id' => 4, 'name' => 'Madhupur', 'bn_name' => 'মধুপুর'],
            ['district_id' => 4, 'name' => 'Ghatail', 'bn_name' => 'ঘাটাইল'],
            ['district_id' => 4, 'name' => 'Kalihati', 'bn_name' => 'কালিহাতী'],
            ['district_id' => 4, 'name' => 'Sakhipur', 'bn_name' => 'সখিপুর'],
            ['district_id' => 4, 'name' => 'Bhuapur', 'bn_name' => 'ভূঞাপুর'],
            ['district_id' => 4, 'name' => 'Basail', 'bn_name' => 'বাসাইল'],
            ['district_id' => 4, 'name' => 'Delduar', 'bn_name' => 'দেলদুয়ার'],
            ['district_id' => 4, 'name' => 'Nagarpur', 'bn_name' => 'নাগরপুর'],
            ['district_id' => 4, 'name' => 'Dhanbari', 'bn_name' => 'ধনবাড়ী'],

            ['district_id' => 5, 'name' => 'Narsingdi Sadar', 'bn_name' => 'নরসিংদী সদর'],
            ['district_id' => 5, 'name' => 'Palash', 'bn_name' => 'পলাশ'],
            ['district_id' => 5, 'name' => 'Shibpur', 'bn_name' => 'শিবপুর'],
            ['district_id' => 5, 'name' => 'Raipura', 'bn_name' => 'রায়পুরা'],
            ['district_id' => 5, 'name' => 'Belabo', 'bn_name' => 'বেলাবো'],
            ['district_id' => 5, 'name' => 'Monohardi', 'bn_name' => 'মনোহরদী'],

            ['district_id' => 6, 'name' => 'Manikganj Sadar', 'bn_name' => 'মানিকগঞ্জ সদর'],
            ['district_id' => 6, 'name' => 'Singair', 'bn_name' => 'সিংগাইর'],
            ['district_id' => 6, 'name' => 'Shibalaya', 'bn_name' => 'শিবালয়'],
            ['district_id' => 6, 'name' => 'Saturia', 'bn_name' => 'সাটুরিয়া'],
            ['district_id' => 6, 'name' => 'Harirampur', 'bn_name' => 'হরিরামপুর'],
            ['district_id' => 6, 'name' => 'Ghior', 'bn_name' => 'ঘিওর'],
            ['district_id' => 6, 'name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],

            ['district_id' => 7, 'name' => 'Munshiganj Sadar', 'bn_name' => 'মুন্সীগঞ্জ সদর'],
            ['district_id' => 7, 'name' => 'Sreenagar', 'bn_name' => 'শ্রীনগর'],
            ['district_id' => 7, 'name' => 'Sirajdikhan', 'bn_name' => 'সিরাজদিখান'],
            ['district_id' => 7, 'name' => 'Louhajang', 'bn_name' => 'লৌহজং'],
            ['district_id' => 7, 'name' => 'Tongibari', 'bn_name' => 'টঙ্গীবাড়ি'],
            ['district_id' => 7, 'name' => 'Gazaria', 'bn_name' => 'গজারিয়া'],

            ['district_id' => 8, 'name' => 'Faridpur Sadar', 'bn_name' => 'ফরিদপুর সদর'],
            ['district_id' => 8, 'name' => 'Boalmari', 'bn_name' => 'বোয়ালমারী'],
            ['district_id' => 8, 'name' => 'Bhanga', 'bn_name' => 'ভাঙ্গা'],
            ['district_id' => 8, 'name' => 'Nagarkanda', 'bn_name' => 'নগরকান্দা'],
            ['district_id' => 8, 'name' => 'Madhukhali', 'bn_name' => 'মধুখালী'],
            ['district_id' => 8, 'name' => 'Sadarpur', 'bn_name' => 'সদরপুর'],
            ['district_id' => 8, 'name' => 'Charbhadrasan', 'bn_name' => 'চরভদ্রাসন'],
            ['district_id' => 8, 'name' => 'Alfadanga', 'bn_name' => 'আলফাডাঙ্গা'],
            ['district_id' => 8, 'name' => 'Saltha', 'bn_name' => 'সালথা'],

            ['district_id' => 9, 'name' => 'Gopalganj Sadar', 'bn_name' => 'গোপালগঞ্জ সদর'],
            ['district_id' => 9, 'name' => 'Kashiani', 'bn_name' => 'কাশিয়ানী'],
            ['district_id' => 9, 'name' => 'Kotalipara', 'bn_name' => 'কোটালীপাড়া'],
            ['district_id' => 9, 'name' => 'Muksudpur', 'bn_name' => 'মুকসুদপুর'],
            ['district_id' => 9, 'name' => 'Tungipara', 'bn_name' => 'টুঙ্গিপাড়া'],

            ['district_id' => 10, 'name' => 'Madaripur Sadar', 'bn_name' => 'মাদারীপুর সদর'],
            ['district_id' => 10, 'name' => 'Shibchar', 'bn_name' => 'শিবচর'],
            ['district_id' => 10, 'name' => 'Kalkini', 'bn_name' => 'কালকিনি'],
            ['district_id' => 10, 'name' => 'Rajoir', 'bn_name' => 'রাজৈর'],
            ['district_id' => 10, 'name' => 'Dasar', 'bn_name' => 'ডাসার'],

            ['district_id' => 11, 'name' => 'Rajbari Sadar', 'bn_name' => 'রাজবাড়ী সদর'],
            ['district_id' => 11, 'name' => 'Goalanda', 'bn_name' => 'গোয়ালন্দ'],
            ['district_id' => 11, 'name' => 'Pangsha', 'bn_name' => 'পাংশা'],
            ['district_id' => 11, 'name' => 'Baliakandi', 'bn_name' => 'বালিয়াকান্দি'],
            ['district_id' => 11, 'name' => 'Kalukhali', 'bn_name' => 'কালুখালী'],

            ['district_id' => 12, 'name' => 'Shariatpur Sadar', 'bn_name' => 'শরীয়তপুর সদর'],
            ['district_id' => 12, 'name' => 'Zajira', 'bn_name' => 'জাজিরা'],
            ['district_id' => 12, 'name' => 'Naria', 'bn_name' => 'নড়িয়া'],
            ['district_id' => 12, 'name' => 'Bhedarganj', 'bn_name' => 'ভেদরগঞ্জ'],
            ['district_id' => 12, 'name' => 'Damudya', 'bn_name' => 'ডামুড্যা'],
            ['district_id' => 12, 'name' => 'Gosairhat', 'bn_name' => 'গোসাইরহাট'],

            ['district_id' => 13, 'name' => 'Kishoreganj Sadar', 'bn_name' => 'কিশোরগঞ্জ সদর'],
            ['district_id' => 13, 'name' => 'Bhairab', 'bn_name' => 'ভৈরব'],
            ['district_id' => 13, 'name' => 'Bajitpur', 'bn_name' => 'বাজিতপুর'],
            ['district_id' => 13, 'name' => 'Kuliarchar', 'bn_name' => 'কুলিয়ারচর'],
            ['district_id' => 13, 'name' => 'Pakundia', 'bn_name' => 'পাকুন্দিয়া'],
            ['district_id' => 13, 'name' => 'Hossainpur', 'bn_name' => 'হোসেনপুর'],
            ['district_id' => 13, 'name' => 'Katiadi', 'bn_name' => 'কটিয়াদী'],
            ['district_id' => 13, 'name' => 'Karimganj', 'bn_name' => 'করিমগঞ্জ'],
            ['district_id' => 13, 'name' => 'Tarail', 'bn_name' => 'তাড়াইল'],
            ['district_id' => 13, 'name' => 'Itna', 'bn_name' => 'ইটনা'],
            ['district_id' => 13, 'name' => 'Mithamoin', 'bn_name' => 'মিঠামইন'],
            ['district_id' => 13, 'name' => 'Austagram', 'bn_name' => 'অষ্টগ্রাম'],
            ['district_id' => 13, 'name' => 'Nikli', 'bn_name' => 'নিকলী'],

            ['district_id' => 14, 'name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী'],
            ['district_id' => 14, 'name' => 'Panchlaish', 'bn_name' => 'পাঁচলাইশ'],
            ['district_id' => 14, 'name' => 'Halishahar', 'bn_name' => 'হালিশহর'],
            ['district_id' => 14, 'name' => 'Pahartali', 'bn_name' => 'পাহাড়তলী'],
            ['district_id' => 14, 'name' => 'Double Mooring', 'bn_name' => 'ডবলমুরিং'],
            ['district_id' => 14, 'name' => 'Chandgaon', 'bn_name' => 'চান্দগাঁও'],
            ['district_id' => 14, 'name' => 'Hathazari', 'bn_name' => 'হাটহাজারী'],
            ['district_id' => 14, 'name' => 'Sitakunda', 'bn_name' => 'সীতাকুণ্ড'],
            ['district_id' => 14, 'name' => 'Mirsharai', 'bn_name' => 'মীরসরাই'],
            ['district_id' => 14, 'name' => 'Patiya', 'bn_name' => 'পটিয়া'],
            ['district_id' => 14, 'name' => 'Boalkhali', 'bn_name' => 'বোয়ালখালী'],
            ['district_id' => 14, 'name' => 'Anwara', 'bn_name' => 'আনোয়ারা'],
            ['district_id' => 14, 'name' => 'Raozan', 'bn_name' => 'রাউজান'],
            ['district_id' => 14, 'name' => 'Rangunia', 'bn_name' => 'রাঙ্গুনিয়া'],
            ['district_id' => 14, 'name' => 'Sandwip', 'bn_name' => 'সন্দ্বীপ'],
            ['district_id' => 14, 'name' => 'Lohagara', 'bn_name' => 'লোহাগাড়া'],
            ['district_id' => 14, 'name' => 'Banshkhali', 'bn_name' => 'বাঁশখালী'],
            ['district_id' => 14, 'name' => 'Satkania', 'bn_name' => 'সাতকানিয়া'],
            ['district_id' => 14, 'name' => 'Karnaphuli', 'bn_name' => 'কর্ণফুলী'],

            ['district_id' => 15, 'name' => 'Cox\'s Bazar Sadar', 'bn_name' => 'কক্সবাজার সদর'],
            ['district_id' => 15, 'name' => 'Chakaria', 'bn_name' => 'চকরিয়া'],
            ['district_id' => 15, 'name' => 'Teknaf', 'bn_name' => 'টেকনাফ'],
            ['district_id' => 15, 'name' => 'Ukhia', 'bn_name' => 'উখিয়া'],
            ['district_id' => 15, 'name' => 'Ramu', 'bn_name' => 'রামু'],
            ['district_id' => 15, 'name' => 'Maheshkhali', 'bn_name' => 'মহেশখালী'],
            ['district_id' => 15, 'name' => 'Kutubdia', 'bn_name' => 'কুতুবদিয়া'],
            ['district_id' => 15, 'name' => 'Pekua', 'bn_name' => 'পেকুয়া'],
            ['district_id' => 15, 'name' => 'Eidgaon', 'bn_name' => 'ঈদগাঁও'],

            ['district_id' => 16, 'name' => 'Cumilla Adarsha Sadar', 'bn_name' => 'কুমিল্লা আদর্শ সদর'],
            ['district_id' => 16, 'name' => 'Cumilla Sadar Dakshin', 'bn_name' => 'কুমিল্লা সদর দক্ষিণ'],
            ['district_id' => 16, 'name' => 'Laksam', 'bn_name' => 'লাকসাম'],
            ['district_id' => 16, 'name' => 'Daudkandi', 'bn_name' => 'দাউদকান্দি'],
            ['district_id' => 16, 'name' => 'Debidwar', 'bn_name' => 'দেবিদ্বার'],
            ['district_id' => 16, 'name' => 'Chandina', 'bn_name' => 'চান্দিনা'],
            ['district_id' => 16, 'name' => 'Barura', 'bn_name' => 'বরুড়া'],
            ['district_id' => 16, 'name' => 'Burichang', 'bn_name' => 'বুড়িচং'],
            ['district_id' => 16, 'name' => 'Brahmanpara', 'bn_name' => 'ব্রাহ্মণপাড়া'],
            ['district_id' => 16, 'name' => 'Chauddagram', 'bn_name' => 'চৌদ্দগ্রাম'],
            ['district_id' => 16, 'name' => 'Homna', 'bn_name' => 'হোমনা'],
            ['district_id' => 16, 'name' => 'Muradnagar', 'bn_name' => 'মুরাদনগর'],
            ['district_id' => 16, 'name' => 'Meghna', 'bn_name' => 'মেঘনা'],
            ['district_id' => 16, 'name' => 'Monohargonj', 'bn_name' => 'মনোহরগঞ্জ'],
            ['district_id' => 16, 'name' => 'Titas', 'bn_name' => 'তিতাস'],
            ['district_id' => 16, 'name' => 'Lalmai', 'bn_name' => 'লালমাই'],

            ['district_id' => 17, 'name' => 'Feni Sadar', 'bn_name' => 'ফেনী সদর'],
            ['district_id' => 17, 'name' => 'Daganbhuiyan', 'bn_name' => 'দাগনভূঞা'],
            ['district_id' => 17, 'name' => 'Chhagalnaiya', 'bn_name' => 'ছাগলনাইয়া'],
            ['district_id' => 17, 'name' => 'Sonagazi', 'bn_name' => 'সোনাগাজী'],
            ['district_id' => 17, 'name' => 'Parshuram', 'bn_name' => 'পরশুরাম'],
            ['district_id' => 17, 'name' => 'Fulgazi', 'bn_name' => 'ফুলগাজী'],

            ['district_id' => 18, 'name' => 'Brahmanbaria Sadar', 'bn_name' => 'ব্রাহ্মণবাড়িয়া সদর'],
            ['district_id' => 18, 'name' => 'Ashuganj', 'bn_name' => 'আশুগঞ্জ'],
            ['district_id' => 18, 'name' => 'Sarail', 'bn_name' => 'সরাইল'],
            ['district_id' => 18, 'name' => 'Nasirnagar', 'bn_name' => 'নাসিরনগর'],
            ['district_id' => 18, 'name' => 'Nabinagar', 'bn_name' => 'নবীনগর'],
            ['district_id' => 18, 'name' => 'Bancharampur', 'bn_name' => 'বাঞ্ছারামপুর'],
            ['district_id' => 18, 'name' => 'Kasba', 'bn_name' => 'কসবা'],
            ['district_id' => 18, 'name' => 'Akhaura', 'bn_name' => 'আখাউড়া'],
            ['district_id' => 18, 'name' => 'Bijoynagar', 'bn_name' => 'বিজয়নগর'],

            ['district_id' => 19, 'name' => 'Rangamati Sadar', 'bn_name' => 'রাঙ্গামাটি সদর'],
            ['district_id' => 19, 'name' => 'Kaptai', 'bn_name' => 'কাপ্তাই'],
            ['district_id' => 19, 'name' => 'Kawkhali', 'bn_name' => 'কাউখালী'],
            ['district_id' => 19, 'name' => 'Baghaichhari', 'bn_name' => 'বাঘাইছড়ি'],
            ['district_id' => 19, 'name' => 'Barkal', 'bn_name' => 'বরকল'],
            ['district_id' => 19, 'name' => 'Langadu', 'bn_name' => 'লংগদু'],
            ['district_id' => 19, 'name' => 'Rajasthali', 'bn_name' => 'রাজস্থলী'],
            ['district_id' => 19, 'name' => 'Belaichhari', 'bn_name' => 'বিলাইছড়ি'],
            ['district_id' => 19, 'name' => 'Juraichhari', 'bn_name' => 'জুরাইছড়ি'],
            ['district_id' => 19, 'name' => 'Naniarchar', 'bn_name' => 'নানিয়ারচর'],

            ['district_id' => 20, 'name' => 'Noakhali Sadar', 'bn_name' => 'নোয়াখালী সদর'],
            ['district_id' => 20, 'name' => 'Begumganj', 'bn_name' => 'বেগমগঞ্জ'],
            ['district_id' => 20, 'name' => 'Chatkhil', 'bn_name' => 'চাটখিল'],
            ['district_id' => 20, 'name' => 'Companiganj', 'bn_name' => 'কোম্পানীগঞ্জ'],
            ['district_id' => 20, 'name' => 'Hatiya', 'bn_name' => 'হাতিয়া'],
            ['district_id' => 20, 'name' => 'Senbagh', 'bn_name' => 'সেনবাগ'],
            ['district_id' => 20, 'name' => 'Sonaimuri', 'bn_name' => 'সোনাইমুড়ী'],
            ['district_id' => 20, 'name' => 'Subarnachar', 'bn_name' => 'সুবর্ণচর'],
            ['district_id' => 20, 'name' => 'Kabirhat', 'bn_name' => 'কবিরহাট'],

            ['district_id' => 21, 'name' => 'Chandpur Sadar', 'bn_name' => 'চাঁদপুর সদর'],
            ['district_id' => 21, 'name' => 'Hajiganj', 'bn_name' => 'হাজীগঞ্জ'],
            ['district_id' => 21, 'name' => 'Kachua', 'bn_name' => 'কচুয়া'],
            ['district_id' => 21, 'name' => 'Faridganj', 'bn_name' => 'ফরিদগঞ্জ'],
            ['district_id' => 21, 'name' => 'Matlab Uttar', 'bn_name' => 'মতলব উত্তর'],
            ['district_id' => 21, 'name' => 'Matlab Dakshin', 'bn_name' => 'মতলব দক্ষিণ'],
            ['district_id' => 21, 'name' => 'Shahrasti', 'bn_name' => 'শাহরাস্তি'],
            ['district_id' => 21, 'name' => 'Haimchar', 'bn_name' => 'হাইমচর'],

            ['district_id' => 22, 'name' => 'Lakshmipur Sadar', 'bn_name' => 'লক্ষ্মীপুর সদর'],
            ['district_id' => 22, 'name' => 'Raipur', 'bn_name' => 'রায়পুর'],
            ['district_id' => 22, 'name' => 'Ramganj', 'bn_name' => 'রামগঞ্জ'],
            ['district_id' => 22, 'name' => 'Ramgati', 'bn_name' => 'রামগতি'],
            ['district_id' => 22, 'name' => 'Kamalnagar', 'bn_name' => 'কমলনগর'],

            ['district_id' => 23, 'name' => 'Khagrachhari Sadar', 'bn_name' => 'খাগড়াছড়ি সদর'],
            ['district_id' => 23, 'name' => 'Dighinala', 'bn_name' => 'দিঘীনালা'],
            ['district_id' => 23, 'name' => 'Panchhari', 'bn_name' => 'পানছড়ি'],
            ['district_id' => 23, 'name' => 'Mahalchhari', 'bn_name' => 'মহালছড়ি'],
            ['district_id' => 23, 'name' => 'Matiranga', 'bn_name' => 'মাটিরাঙ্গা'],
            ['district_id' => 23, 'name' => 'Manikchhari', 'bn_name' => 'মানিকছড়ি'],
            ['district_id' => 23, 'name' => 'Ramgarh', 'bn_name' => 'রামগড়'],
            ['district_id' => 23, 'name' => 'Lakshmichhari', 'bn_name' => 'লক্ষ্মীছড়ি'],
            ['district_id' => 23, 'name' => 'Guimara', 'bn_name' => 'গুইমারা'],

            ['district_id' => 24, 'name' => 'Bandarban Sadar', 'bn_name' => 'বান্দরবান সদর'],
            ['district_id' => 24, 'name' => 'Ruma', 'bn_name' => 'রুমা'],
            ['district_id' => 24, 'name' => 'Thanchi', 'bn_name' => 'থানচি'],
            ['district_id' => 24, 'name' => 'Rowangchhari', 'bn_name' => 'রোয়াংছড়ি'],
            ['district_id' => 24, 'name' => 'Lama', 'bn_name' => 'লামা'],
            ['district_id' => 24, 'name' => 'Alikadam', 'bn_name' => 'আলীকদম'],
            ['district_id' => 24, 'name' => 'Naikhongchhari', 'bn_name' => 'নাইক্ষ্যংছড়ি'],

            ['district_id' => 25, 'name' => 'Boalia', 'bn_name' => 'বোয়ালিয়া'],
            ['district_id' => 25, 'name' => 'Motihar', 'bn_name' => 'মতিহার'],
            ['district_id' => 25, 'name' => 'Rajpara', 'bn_name' => 'রাজপাড়া'],
            ['district_id' => 25, 'name' => 'Shah Makhdum', 'bn_name' => 'শাহ মখদুম'],
            ['district_id' => 25, 'name' => 'Paba', 'bn_name' => 'পবা'],
            ['district_id' => 25, 'name' => 'Godagari', 'bn_name' => 'গোদাগাড়ী'],
            ['district_id' => 25, 'name' => 'Tanore', 'bn_name' => 'তানোর'],
            ['district_id' => 25, 'name' => 'Bagmara', 'bn_name' => 'বাগমারা'],
            ['district_id' => 25, 'name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর'],
            ['district_id' => 25, 'name' => 'Charghat', 'bn_name' => 'চারঘাট'],
            ['district_id' => 25, 'name' => 'Bagha', 'bn_name' => 'বাঘা'],
            ['district_id' => 25, 'name' => 'Puthia', 'bn_name' => 'পুঠিয়া'],
            ['district_id' => 25, 'name' => 'Mohanpur', 'bn_name' => 'মোহনপুর'],

            ['district_id' => 26, 'name' => 'Bogura Sadar', 'bn_name' => 'বগুড়া সদর'],
            ['district_id' => 26, 'name' => 'Shajahanpur', 'bn_name' => 'শাজাহানপুর'],
            ['district_id' => 26, 'name' => 'Sherpur', 'bn_name' => 'শেরপুর'],
            ['district_id' => 26, 'name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ'],
            ['district_id' => 26, 'name' => 'Gabtali', 'bn_name' => 'গাবতলী'],
            ['district_id' => 26, 'name' => 'Kahaloo', 'bn_name' => 'কাহালু'],
            ['district_id' => 26, 'name' => 'Nandigram', 'bn_name' => 'নন্দীগ্রাম'],
            ['district_id' => 26, 'name' => 'Dhunat', 'bn_name' => 'ধুনট'],
            ['district_id' => 26, 'name' => 'Sariakandi', 'bn_name' => 'সারিয়াকান্দি'],
            ['district_id' => 26, 'name' => 'Sonatala', 'bn_name' => 'সোনাতলা'],
            ['district_id' => 26, 'name' => 'Adamdighi', 'bn_name' => 'আদমদিঘী'],
            ['district_id' => 26, 'name' => 'Dupchanchia', 'bn_name' => 'দুপচাঁচিয়া'],

            ['district_id' => 27, 'name' => 'Pabna Sadar', 'bn_name' => 'পাবনা সদর'],
            ['district_id' => 27, 'name' => 'Ishwardi', 'bn_name' => 'ঈশ্বরদী'],
            ['district_id' => 27, 'name' => 'Santhia', 'bn_name' => 'সাঁথিয়া'],
            ['district_id' => 27, 'name' => 'Chatmohar', 'bn_name' => 'চাটমোহর'],
            ['district_id' => 27, 'name' => 'Sujanagar', 'bn_name' => 'সুজানগর'],
            ['district_id' => 27, 'name' => 'Bera', 'bn_name' => 'বেড়া'],
            ['district_id' => 27, 'name' => 'Atgharia', 'bn_name' => 'আটঘরিয়া'],
            ['district_id' => 27, 'name' => 'Bhangura', 'bn_name' => 'ভাঙ্গুড়া'],
            ['district_id' => 27, 'name' => 'Faridpur', 'bn_name' => 'ফরিদপুর'],

            ['district_id' => 28, 'name' => 'Sirajganj Sadar', 'bn_name' => 'সিরাজগঞ্জ সদর'],
            ['district_id' => 28, 'name' => 'Shahjadpur', 'bn_name' => 'শাহজাদপুর'],
            ['district_id' => 28, 'name' => 'Ullapara', 'bn_name' => 'উল্লাপাড়া'],
            ['district_id' => 28, 'name' => 'Belkuchi', 'bn_name' => 'বেলকুচি'],
            ['district_id' => 28, 'name' => 'Kazipur', 'bn_name' => 'কাজীপুর'],
            ['district_id' => 28, 'name' => 'Tarash', 'bn_name' => 'তাড়াশ'],
            ['district_id' => 28, 'name' => 'Kamarkhanda', 'bn_name' => 'কামারখন্দ'],
            ['district_id' => 28, 'name' => 'Raiganj', 'bn_name' => 'রায়গঞ্জ'],
            ['district_id' => 28, 'name' => 'Chauhali', 'bn_name' => 'চৌহালী'],

            ['district_id' => 29, 'name' => 'Naogaon Sadar', 'bn_name' => 'নওগাঁ সদর'],
            ['district_id' => 29, 'name' => 'Manda', 'bn_name' => 'মান্দা'],
            ['district_id' => 29, 'name' => 'Patnitala', 'bn_name' => 'পত্নীতলা'],
            ['district_id' => 29, 'name' => 'Dhamoirhat', 'bn_name' => 'ধামইরহাট'],
            ['district_id' => 29, 'name' => 'Sapahar', 'bn_name' => 'সাপাহার'],
            ['district_id' => 29, 'name' => 'Porsha', 'bn_name' => 'পোরশা'],
            ['district_id' => 29, 'name' => 'Niamatpur', 'bn_name' => 'নিয়ামতপুর'],
            ['district_id' => 29, 'name' => 'Atrai', 'bn_name' => 'আত্রাই'],
            ['district_id' => 29, 'name' => 'Raninagar', 'bn_name' => 'রাণীনগর'],
            ['district_id' => 29, 'name' => 'Badalgachhi', 'bn_name' => 'বদলগাছী'],
            ['district_id' => 29, 'name' => 'Mohadevpur', 'bn_name' => 'মহাদেবপুর'],

            ['district_id' => 30, 'name' => 'Natore Sadar', 'bn_name' => 'নাটোর সদর'],
            ['district_id' => 30, 'name' => 'Singra', 'bn_name' => 'সিংড়া'],
            ['district_id' => 30, 'name' => 'Baraigram', 'bn_name' => 'বড়াইগ্রাম'],
            ['district_id' => 30, 'name' => 'Bagatipara', 'bn_name' => 'বাগাতিপাড়া'],
            ['district_id' => 30, 'name' => 'Lalpur', 'bn_name' => 'লালপুর'],
            ['district_id' => 30, 'name' => 'Gurudaspur', 'bn_name' => 'গুরুদাসপুর'],
            ['district_id' => 30, 'name' => 'Naldanga', 'bn_name' => 'নলডাঙ্গা'],

            ['district_id' => 31, 'name' => 'Chapainawabganj Sadar', 'bn_name' => 'চাঁপাইনবাবগঞ্জ সদর'],
            ['district_id' => 31, 'name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ'],
            ['district_id' => 31, 'name' => 'Gomastapur', 'bn_name' => 'গোমস্তাপুর'],
            ['district_id' => 31, 'name' => 'Nachole', 'bn_name' => 'নাচোল'],
            ['district_id' => 31, 'name' => 'Bholahat', 'bn_name' => 'ভোলাহাট'],

            ['district_id' => 32, 'name' => 'Joypurhat Sadar', 'bn_name' => 'জয়পুরহাট সদর'],
            ['district_id' => 32, 'name' => 'Panchbibi', 'bn_name' => 'পাঁচবিবি'],
            ['district_id' => 32, 'name' => 'Kalai', 'bn_name' => 'কালাই'],
            ['district_id' => 32, 'name' => 'Khetlal', 'bn_name' => 'ক্ষেতলাল'],
            ['district_id' => 32, 'name' => 'Akkelpur', 'bn_name' => 'আক্কেলপুর'],

            ['district_id' => 33, 'name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী'],
            ['district_id' => 33, 'name' => 'Sonadanga', 'bn_name' => 'সোনাডাঙ্গা'],
            ['district_id' => 33, 'name' => 'Khalishpur', 'bn_name' => 'খালিশপুর'],
            ['district_id' => 33, 'name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],
            ['district_id' => 33, 'name' => 'Khan Jahan Ali', 'bn_name' => 'খান জাহান আলী'],
            ['district_id' => 33, 'name' => 'Dumuria', 'bn_name' => 'ডুমুরিয়া'],
            ['district_id' => 33, 'name' => 'Batiaghata', 'bn_name' => 'বটিয়াঘাটা'],
            ['district_id' => 33, 'name' => 'Rupsha', 'bn_name' => 'রূপসা'],
            ['district_id' => 33, 'name' => 'Phultala', 'bn_name' => 'ফুলতলা'],
            ['district_id' => 33, 'name' => 'Dighalia', 'bn_name' => 'দিঘলিয়া'],
            ['district_id' => 33, 'name' => 'Paikgachha', 'bn_name' => 'পাইকগাছা'],
            ['district_id' => 33, 'name' => 'Koyra', 'bn_name' => 'কয়রা'],
            ['district_id' => 33, 'name' => 'Terokhada', 'bn_name' => 'তেরখাদা'],
            ['district_id' => 33, 'name' => 'Dacope', 'bn_name' => 'দাকোপ'],

            ['district_id' => 34, 'name' => 'Jashore Sadar', 'bn_name' => 'যশোর সদর'],
            ['district_id' => 34, 'name' => 'Jhikargachha', 'bn_name' => 'ঝিকরগাছা'],
            ['district_id' => 34, 'name' => 'Sharsha', 'bn_name' => 'শার্শা'],
            ['district_id' => 34, 'name' => 'Manirampur', 'bn_name' => 'মণিরামপুর'],
            ['district_id' => 34, 'name' => 'Keshabpur', 'bn_name' => 'কেশবপুর'],
            ['district_id' => 34, 'name' => 'Abhaynagar', 'bn_name' => 'অভয়নগর'],
            ['district_id' => 34, 'name' => 'Bagherpara', 'bn_name' => 'বাঘারপাড়া'],
            ['district_id' => 34, 'name' => 'Chaugachha', 'bn_name' => 'চৌগাছা'],

            ['district_id' => 35, 'name' => 'Satkhira Sadar', 'bn_name' => 'সাতক্ষীরা সদর'],
            ['district_id' => 35, 'name' => 'Kalaroa', 'bn_name' => 'কলারোয়া'],
            ['district_id' => 35, 'name' => 'Tala', 'bn_name' => 'তালা'],
            ['district_id' => 35, 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
            ['district_id' => 35, 'name' => 'Shyamnagar', 'bn_name' => 'শ্যামনগর'],
            ['district_id' => 35, 'name' => 'Debhata', 'bn_name' => 'দেবহাটা'],
            ['district_id' => 35, 'name' => 'Assasuni', 'bn_name' => 'আশাশুনি'],

            ['district_id' => 36, 'name' => 'Kushtia Sadar', 'bn_name' => 'কুষ্টিয়া সদর'],
            ['district_id' => 36, 'name' => 'Kumarkhali', 'bn_name' => 'কুমারখালী'],
            ['district_id' => 36, 'name' => 'Bheramara', 'bn_name' => 'ভেড়ামারা'],
            ['district_id' => 36, 'name' => 'Mirpur', 'bn_name' => 'মিরপুর'],
            ['district_id' => 36, 'name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],
            ['district_id' => 36, 'name' => 'Khoksa', 'bn_name' => 'খোকসা'],

            ['district_id' => 37, 'name' => 'Jhenaidah Sadar', 'bn_name' => 'ঝিনাইদহ সদর'],
            ['district_id' => 37, 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
            ['district_id' => 37, 'name' => 'Kotchandpur', 'bn_name' => 'কোটচাঁদপুর'],
            ['district_id' => 37, 'name' => 'Maheshpur', 'bn_name' => 'মহেশপুর'],
            ['district_id' => 37, 'name' => 'Shailkupa', 'bn_name' => 'শৈলকুপা'],
            ['district_id' => 37, 'name' => 'Harinakunda', 'bn_name' => 'হরিণাকুণ্ডু'],

            ['district_id' => 38, 'name' => 'Bagerhat Sadar', 'bn_name' => 'বাগেরহাট সদর'],
            ['district_id' => 38, 'name' => 'Mongla', 'bn_name' => 'মোংলা'],
            ['district_id' => 38, 'name' => 'Rampal', 'bn_name' => 'রামপাল'],
            ['district_id' => 38, 'name' => 'Morrelganj', 'bn_name' => 'মোরেলগঞ্জ'],
            ['district_id' => 38, 'name' => 'Fakirhat', 'bn_name' => 'ফকিরহাট'],
            ['district_id' => 38, 'name' => 'Kachua', 'bn_name' => 'কচুয়া'],
            ['district_id' => 38, 'name' => 'Mollahat', 'bn_name' => 'মোল্লাহাট'],
            ['district_id' => 38, 'name' => 'Sarankhola', 'bn_name' => 'শরণখোলা'],
            ['district_id' => 38, 'name' => 'Chitalmari', 'bn_name' => 'চিতলমারী'],

            ['district_id' => 39, 'name' => 'Chuadanga Sadar', 'bn_name' => 'চুয়াডাঙ্গা সদর'],
            ['district_id' => 39, 'name' => 'Alamdanga', 'bn_name' => 'আলমডাঙ্গা'],
            ['district_id' => 39, 'name' => 'Damurhuda', 'bn_name' => 'দামুড়হুদা'],
            ['district_id' => 39, 'name' => 'Jibannagar', 'bn_name' => 'জীবননগর'],

            ['district_id' => 40, 'name' => 'Magura Sadar', 'bn_name' => 'মাগুরা সদর'],
            ['district_id' => 40, 'name' => 'Sreepur', 'bn_name' => 'শ্রীপুর'],
            ['district_id' => 40, 'name' => 'Mohammadpur', 'bn_name' => 'মহম্মদপুর'],
            ['district_id' => 40, 'name' => 'Shalikha', 'bn_name' => 'শালিখা'],

            ['district_id' => 41, 'name' => 'Meherpur Sadar', 'bn_name' => 'মেহেরপুর সদর'],
            ['district_id' => 41, 'name' => 'Gangni', 'bn_name' => 'গাংনী'],
            ['district_id' => 41, 'name' => 'Mujibnagar', 'bn_name' => 'মুজিবনগর'],

            ['district_id' => 42, 'name' => 'Narail Sadar', 'bn_name' => 'নড়াইল সদর'],
            ['district_id' => 42, 'name' => 'Lohagara', 'bn_name' => 'লোহাগড়া'],
            ['district_id' => 42, 'name' => 'Kalia', 'bn_name' => 'কালিয়া'],

            ['district_id' => 43, 'name' => 'Barishal Sadar', 'bn_name' => 'বরিশাল সদর'],
            ['district_id' => 43, 'name' => 'Babuganj', 'bn_name' => 'বাবুগঞ্জ'],
            ['district_id' => 43, 'name' => 'Bakerganj', 'bn_name' => 'বাকেরগঞ্জ'],
            ['district_id' => 43, 'name' => 'Banaripara', 'bn_name' => 'বানারীপাড়া'],
            ['district_id' => 43, 'name' => 'Gournadi', 'bn_name' => 'গৌরনদী'],
            ['district_id' => 43, 'name' => 'Agailjhara', 'bn_name' => 'আগৈলঝাড়া'],
            ['district_id' => 43, 'name' => 'Mehendiganj', 'bn_name' => 'মেহেন্দিগঞ্জ'],
            ['district_id' => 43, 'name' => 'Muladi', 'bn_name' => 'মুলাদী'],
            ['district_id' => 43, 'name' => 'Wazirpur', 'bn_name' => 'উজিরপুর'],
            ['district_id' => 43, 'name' => 'Hizla', 'bn_name' => 'হিজলা'],

            ['district_id' => 44, 'name' => 'Patuakhali Sadar', 'bn_name' => 'পটুয়াখালী সদর'],
            ['district_id' => 44, 'name' => 'Galachipa', 'bn_name' => 'গলাচিপা'],
            ['district_id' => 44, 'name' => 'Bauphal', 'bn_name' => 'বাউফল'],
            ['district_id' => 44, 'name' => 'Kalapara', 'bn_name' => 'কলাপাড়া'],
            ['district_id' => 44, 'name' => 'Mirzaganj', 'bn_name' => 'মির্জাগঞ্জ'],
            ['district_id' => 44, 'name' => 'Dumki', 'bn_name' => 'দুমকি'],
            ['district_id' => 44, 'name' => 'Rangabali', 'bn_name' => 'রাঙ্গাবালী'],

            ['district_id' => 45, 'name' => 'Bhola Sadar', 'bn_name' => 'ভোলা সদর'],
            ['district_id' => 45, 'name' => 'Borhanuddin', 'bn_name' => 'বোরহানউদ্দিন'],
            ['district_id' => 45, 'name' => 'Char Fasson', 'bn_name' => 'চরফ্যাশন'],
            ['district_id' => 45, 'name' => 'Daulatkhan', 'bn_name' => 'দৌলতখান'],
            ['district_id' => 45, 'name' => 'Lalmohan', 'bn_name' => 'লালমোহন'],
            ['district_id' => 45, 'name' => 'Tazumuddin', 'bn_name' => 'তজুমদ্দিন'],
            ['district_id' => 45, 'name' => 'Monpura', 'bn_name' => 'মনপুরা'],

            ['district_id' => 46, 'name' => 'Pirojpur Sadar', 'bn_name' => 'পিরোজপুর সদর'],
            ['district_id' => 46, 'name' => 'Bhandaria', 'bn_name' => 'ভাণ্ডারিয়া'],
            ['district_id' => 46, 'name' => 'Mathbaria', 'bn_name' => 'মঠবাড়িয়া'],
            ['district_id' => 46, 'name' => 'Kawkhali', 'bn_name' => 'কাউখালী'],
            ['district_id' => 46, 'name' => 'Nazirpur', 'bn_name' => 'নাজিরপুর'],
            ['district_id' => 46, 'name' => 'Nesarabad', 'bn_name' => 'নেছারাবাদ'],
            ['district_id' => 46, 'name' => 'Zianagar', 'bn_name' => 'জিয়ানগর'],

            ['district_id' => 47, 'name' => 'Barguna Sadar', 'bn_name' => 'বরগুনা সদর'],
            ['district_id' => 47, 'name' => 'Amtali', 'bn_name' => 'আমতলী'],
            ['district_id' => 47, 'name' => 'Patharghata', 'bn_name' => 'পাথরঘাটা'],
            ['district_id' => 47, 'name' => 'Betagi', 'bn_name' => 'বেতাগী'],
            ['district_id' => 47, 'name' => 'Bamna', 'bn_name' => 'বামনা'],
            ['district_id' => 47, 'name' => 'Taltali', 'bn_name' => 'তালতলী'],

            ['district_id' => 48, 'name' => 'Jhalokati Sadar', 'bn_name' => 'ঝালকাঠি সদর'],
            ['district_id' => 48, 'name' => 'Kathalia', 'bn_name' => 'কাঠালিয়া'],
            ['district_id' => 48, 'name' => 'Nalchity', 'bn_name' => 'নলছিটি'],
            ['district_id' => 48, 'name' => 'Rajapur', 'bn_name' => 'রাজাপুর'],

            ['district_id' => 49, 'name' => 'Sylhet Sadar', 'bn_name' => 'সিলেট সদর'],
            ['district_id' => 49, 'name' => 'Beanibazar', 'bn_name' => 'বিয়ানীবাজার'],
            ['district_id' => 49, 'name' => 'Golapganj', 'bn_name' => 'গোলাপগঞ্জ'],
            ['district_id' => 49, 'name' => 'Zakiganj', 'bn_name' => 'জকিগঞ্জ'],
            ['district_id' => 49, 'name' => 'Kanaighat', 'bn_name' => 'কানাইঘাট'],
            ['district_id' => 49, 'name' => 'Fenchuganj', 'bn_name' => 'ফেঞ্চুগঞ্জ'],
            ['district_id' => 49, 'name' => 'Balaganj', 'bn_name' => 'বালাগঞ্জ'],
            ['district_id' => 49, 'name' => 'Bishwanath', 'bn_name' => 'বিশ্বনাথ'],
            ['district_id' => 49, 'name' => 'Companiganj', 'bn_name' => 'কোম্পানীগঞ্জ'],
            ['district_id' => 49, 'name' => 'Gowainghat', 'bn_name' => 'গোয়াইনঘাট'],
            ['district_id' => 49, 'name' => 'Jaintiapur', 'bn_name' => 'জৈন্তাপুর'],
            ['district_id' => 49, 'name' => 'Dakshin Surma', 'bn_name' => 'দক্ষিণ সুরমা'],
            ['district_id' => 49, 'name' => 'Osmani Nagar', 'bn_name' => 'ওসমানী নগর'],

            ['district_id' => 50, 'name' => 'Moulvibazar Sadar', 'bn_name' => 'মৌলভীবাজার সদর'],
            ['district_id' => 50, 'name' => 'Sreemangal', 'bn_name' => 'শ্রীমঙ্গল'],
            ['district_id' => 50, 'name' => 'Kulaura', 'bn_name' => 'কুলাউড়া'],
            ['district_id' => 50, 'name' => 'Kamalganj', 'bn_name' => 'কমলগঞ্জ'],
            ['district_id' => 50, 'name' => 'Barlekha', 'bn_name' => 'বড়লেখা'],
            ['district_id' => 50, 'name' => 'Rajnagar', 'bn_name' => 'রাজনগর'],
            ['district_id' => 50, 'name' => 'Juri', 'bn_name' => 'জুড়ী'],

            ['district_id' => 51, 'name' => 'Habiganj Sadar', 'bn_name' => 'হবিগঞ্জ সদর'],
            ['district_id' => 51, 'name' => 'Madhabpur', 'bn_name' => 'মাধবপুর'],
            ['district_id' => 51, 'name' => 'Nabiganj', 'bn_name' => 'নবীগঞ্জ'],
            ['district_id' => 51, 'name' => 'Chunarughat', 'bn_name' => 'চুনারুঘাট'],
            ['district_id' => 51, 'name' => 'Bahubal', 'bn_name' => 'বাহুবল'],
            ['district_id' => 51, 'name' => 'Baniachong', 'bn_name' => 'বানিয়াচং'],
            ['district_id' => 51, 'name' => 'Lakhai', 'bn_name' => 'লাখাই'],
            ['district_id' => 51, 'name' => 'Ajmiriganj', 'bn_name' => 'আজমিরীগঞ্জ'],
            ['district_id' => 51, 'name' => 'Shayestaganj', 'bn_name' => 'শায়েস্তাগঞ্জ'],

            ['district_id' => 52, 'name' => 'Sunamganj Sadar', 'bn_name' => 'সুনামগঞ্জ সদর'],
            ['district_id' => 52, 'name' => 'Chhatak', 'bn_name' => 'ছাতক'],
            ['district_id' => 52, 'name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর'],
            ['district_id' => 52, 'name' => 'Derai', 'bn_name' => 'দিরাই'],
            ['district_id' => 52, 'name' => 'Tahirpur', 'bn_name' => 'তাহিরপুর'],
            ['district_id' => 52, 'name' => 'Dharampasha', 'bn_name' => 'ধর্মপাশা'],
            ['district_id' => 52, 'name' => 'Jamalganj', 'bn_name' => 'জামালগঞ্জ'],
            ['district_id' => 52, 'name' => 'Shantiganj', 'bn_name' => 'শান্তিগঞ্জ'],
            ['district_id' => 52, 'name' => 'Shalla', 'bn_name' => 'শাল্লা'],
            ['district_id' => 52, 'name' => 'Bishwamvarpur', 'bn_name' => 'বিশ্বম্ভরপুর'],
            ['district_id' => 52, 'name' => 'Dowarabazar', 'bn_name' => 'দোয়ারাবাজার'],
            ['district_id' => 52, 'name' => 'Madhyanagar', 'bn_name' => 'মধ্যনগর'],

            ['district_id' => 53, 'name' => 'Rangpur Sadar', 'bn_name' => 'রংপুর সদর'],
            ['district_id' => 53, 'name' => 'Pirgachha', 'bn_name' => 'পীরগাছা'],
            ['district_id' => 53, 'name' => 'Mithapukur', 'bn_name' => 'মিঠাপুকুর'],
            ['district_id' => 53, 'name' => 'Badarganj', 'bn_name' => 'বদরগঞ্জ'],
            ['district_id' => 53, 'name' => 'Gangachhara', 'bn_name' => 'গঙ্গাচড়া'],
            ['district_id' => 53, 'name' => 'Kaunia', 'bn_name' => 'কাউনিয়া'],
            ['district_id' => 53, 'name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ'],
            ['district_id' => 53, 'name' => 'Taraganj', 'bn_name' => 'তারাগঞ্জ'],

            ['district_id' => 54, 'name' => 'Dinajpur Sadar', 'bn_name' => 'দিনাজপুর সদর'],
            ['district_id' => 54, 'name' => 'Birganj', 'bn_name' => 'বীরগঞ্জ'],
            ['district_id' => 54, 'name' => 'Kaharole', 'bn_name' => 'কাহারোল'],
            ['district_id' => 54, 'name' => 'Biral', 'bn_name' => 'বিরল'],
            ['district_id' => 54, 'name' => 'Bochaganj', 'bn_name' => 'বোচাগঞ্জ'],
            ['district_id' => 54, 'name' => 'Parbatipur', 'bn_name' => 'পার্বতীপুর'],
            ['district_id' => 54, 'name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ী'],
            ['district_id' => 54, 'name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ'],
            ['district_id' => 54, 'name' => 'Ghoraghat', 'bn_name' => 'ঘোড়াঘাট'],
            ['district_id' => 54, 'name' => 'Hakimpur', 'bn_name' => 'হাকিমপুর'],
            ['district_id' => 54, 'name' => 'Chirirbandar', 'bn_name' => 'চিরিরবন্দর'],
            ['district_id' => 54, 'name' => 'Khansama', 'bn_name' => 'খানসামা'],

            ['district_id' => 55, 'name' => 'Gaibandha Sadar', 'bn_name' => 'গাইবান্ধা সদর'],
            ['district_id' => 55, 'name' => 'Gobindaganj', 'bn_name' => 'গোবিন্দগঞ্জ'],
            ['district_id' => 55, 'name' => 'Palashbari', 'bn_name' => 'পলাশবাড়ী'],
            ['district_id' => 55, 'name' => 'Sundarganj', 'bn_name' => 'সুন্দরগঞ্জ'],
            ['district_id' => 55, 'name' => 'Sadullapur', 'bn_name' => 'সাদুল্লাপুর'],
            ['district_id' => 55, 'name' => 'Saghata', 'bn_name' => 'সাঘাটা'],
            ['district_id' => 55, 'name' => 'Phulchhari', 'bn_name' => 'ফুলছড়ি'],

            ['district_id' => 56, 'name' => 'Kurigram Sadar', 'bn_name' => 'কুড়িগ্রাম সদর'],
            ['district_id' => 56, 'name' => 'Nageshwari', 'bn_name' => 'নাগেশ্বরী'],
            ['district_id' => 56, 'name' => 'Bhurungamari', 'bn_name' => 'ভুরুঙ্গামারী'],
            ['district_id' => 56, 'name' => 'Ulipur', 'bn_name' => 'উলিপুর'],
            ['district_id' => 56, 'name' => 'Chilmari', 'bn_name' => 'চিলমারী'],
            ['district_id' => 56, 'name' => 'Rajarhat', 'bn_name' => 'রাজারহাট'],
            ['district_id' => 56, 'name' => 'Rowmari', 'bn_name' => 'রৌমারী'],
            ['district_id' => 56, 'name' => 'Char Rajibpur', 'bn_name' => 'চর রাজিবপুর'],

            ['district_id' => 57, 'name' => 'Lalmonirhat Sadar', 'bn_name' => 'লালমনিরহাট সদর'],
            ['district_id' => 57, 'name' => 'Patgram', 'bn_name' => 'পাটগ্রাম'],
            ['district_id' => 57, 'name' => 'Hatibandha', 'bn_name' => 'হাতীবান্ধা'],
            ['district_id' => 57, 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
            ['district_id' => 57, 'name' => 'Aditmari', 'bn_name' => 'আদিতমারী'],

            ['district_id' => 58, 'name' => 'Nilphamari Sadar', 'bn_name' => 'নীলফামারী সদর'],
            ['district_id' => 58, 'name' => 'Saidpur', 'bn_name' => 'সৈয়দপুর'],
            ['district_id' => 58, 'name' => 'Jaldhaka', 'bn_name' => 'জলঢাকা'],
            ['district_id' => 58, 'name' => 'Kishoreganj', 'bn_name' => 'কিশোরগঞ্জ'],
            ['district_id' => 58, 'name' => 'Domar', 'bn_name' => 'ডোমার'],
            ['district_id' => 58, 'name' => 'Dimla', 'bn_name' => 'ডিমলা'],

            ['district_id' => 59, 'name' => 'Panchagarh Sadar', 'bn_name' => 'পঞ্চগড় সদর'],
            ['district_id' => 59, 'name' => 'Tetulia', 'bn_name' => 'তেঁতুলিয়া'],
            ['district_id' => 59, 'name' => 'Boda', 'bn_name' => 'বোদা'],
            ['district_id' => 59, 'name' => 'Atwari', 'bn_name' => 'আটোয়ারী'],
            ['district_id' => 59, 'name' => 'Debiganj', 'bn_name' => 'দেবীগঞ্জ'],

            ['district_id' => 60, 'name' => 'Thakurgaon Sadar', 'bn_name' => 'ঠাকুরগাঁও সদর'],
            ['district_id' => 60, 'name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ'],
            ['district_id' => 60, 'name' => 'Ranisankail', 'bn_name' => 'রাণীশংকৈল'],
            ['district_id' => 60, 'name' => 'Baliadangi', 'bn_name' => 'বালিয়াডাঙ্গী'],
            ['district_id' => 60, 'name' => 'Haripur', 'bn_name' => 'হরিপুর'],

            ['district_id' => 61, 'name' => 'Mymensingh Sadar', 'bn_name' => 'ময়মনসিংহ সদর'],
            ['district_id' => 61, 'name' => 'Muktagachha', 'bn_name' => 'মুক্তাগাছা'],
            ['district_id' => 61, 'name' => 'Trishal', 'bn_name' => 'ত্রিশাল'],
            ['district_id' => 61, 'name' => 'Bhaluka', 'bn_name' => 'ভালুকা'],
            ['district_id' => 61, 'name' => 'Fulbaria', 'bn_name' => 'ফুলবাড়িয়া'],
            ['district_id' => 61, 'name' => 'Gafargaon', 'bn_name' => 'গফরগাঁও'],
            ['district_id' => 61, 'name' => 'Gouripur', 'bn_name' => 'গৌরীপুর'],
            ['district_id' => 61, 'name' => 'Ishwarganj', 'bn_name' => 'ঈশ্বরগঞ্জ'],
            ['district_id' => 61, 'name' => 'Nandail', 'bn_name' => 'নান্দাইল'],
            ['district_id' => 61, 'name' => 'Haluaghat', 'bn_name' => 'হালুয়াঘাট'],
            ['district_id' => 61, 'name' => 'Dhobaura', 'bn_name' => 'ধোবাউড়া'],
            ['district_id' => 61, 'name' => 'Tara Khanda', 'bn_name' => 'তারাকান্দা'],

            ['district_id' => 62, 'name' => 'Jamalpur Sadar', 'bn_name' => 'জামালপুর সদর'],
            ['district_id' => 62, 'name' => 'Melandaha', 'bn_name' => 'মেলান্দহ'],
            ['district_id' => 62, 'name' => 'Islampur', 'bn_name' => 'ইসলামপুর'],
            ['district_id' => 62, 'name' => 'Dewanganj', 'bn_name' => 'দেওয়ানগঞ্জ'],
            ['district_id' => 62, 'name' => 'Sarishabari', 'bn_name' => 'সরিষাবাড়ী'],
            ['district_id' => 62, 'name' => 'Madarganj', 'bn_name' => 'মাদারগঞ্জ'],
            ['district_id' => 62, 'name' => 'Bakshiganj', 'bn_name' => 'বকশীগঞ্জ'],

            ['district_id' => 63, 'name' => 'Netrokona Sadar', 'bn_name' => 'নেত্রকোণা সদর'],
            ['district_id' => 63, 'name' => 'Kendua', 'bn_name' => 'কেন্দুয়া'],
            ['district_id' => 63, 'name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর'],
            ['district_id' => 63, 'name' => 'Kalmakanda', 'bn_name' => 'কলমাকান্দা'],
            ['district_id' => 63, 'name' => 'Barhatta', 'bn_name' => 'বারহাট্টা'],
            ['district_id' => 63, 'name' => 'Atpara', 'bn_name' => 'আটপাড়া'],
            ['district_id' => 63, 'name' => 'Madan', 'bn_name' => 'মদন'],
            ['district_id' => 63, 'name' => 'Khaliajuri', 'bn_name' => 'খালিয়াজুরী'],
            ['district_id' => 63, 'name' => 'Purbadhala', 'bn_name' => 'পূর্বধলা'],

            ['district_id' => 64, 'name' => 'Sherpur Sadar', 'bn_name' => 'শেরপুর সদর'],
            ['district_id' => 64, 'name' => 'Nalitabari', 'bn_name' => 'নালিতাবাড়ী'],
            ['district_id' => 64, 'name' => 'Nakla', 'bn_name' => 'নকলা'],
            ['district_id' => 64, 'name' => 'Jhenaigati', 'bn_name' => 'ঝিনাইগাতী'],
            ['district_id' => 64, 'name' => 'Sreebardi', 'bn_name' => 'শ্রীবরদী'],
        ];

        foreach (array_chunk($upazilas, 100) as $chunk) {
            $records = array_map(function ($item) use ($now) {
                return array_merge($item, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }, $chunk);

            DB::table('upazilas')->insert($records);
        }
    }
}
